### ISSUE TITLE
Can´t setup docker

### ISSUE THREAD

**Issue by MattiasNilsson** [t3kit/t3kit_docker#5]
When trying to use the Docker instance for t3kit we get the following error:

https://www.dropbox.com/s/ba50v95bni0fcwl/Sk%C3%A4rmklipp%202017-01-16%2009.16.42.png?dl=0

**Comment by MattiasNilsson** [comment]
@laurisaarni ping!

**Comment by laurisaarni** [comment]
@MattiasNilsson does the user have local Apache or Nginx running on port 80?
We would also need to know Docker version used on the Mac.

**Comment by MattiasNilsson** [comment]
@laurisaarni Yes the user is running a local apache instance on port 80. And the docker version is: 
Version 1.13.0-rc5-beta35 (14875)
Channel: Beta
25211e84dd

**Comment by limchivy** [comment]
@MattiasNilsson I think it is conflict binding port. May you stop the Apache service first?
**Note:** It is working fine on my Ubuntu 14.04.

**Comment by laurisaarni** [comment]
@limchivy is right. If the Apache runs locally it binds the port and Docker will be blocked. If they need to run the Apache at the same time they need to fork the dockert3kit repo and add another port to docker-compose file to expose web container.

**Comment by MattiasNilsson** [comment]
Alright thanks for the feedback, will add this to the readme.
